package lista_array;

/**
 * CRIE UM ARRAY DE INTEIROS DETAMANHO 10.
 * IMPLEMENTE UM PROGRAMA QUE DEFINA E ESCREVA O ARRAY,
 * BEM COMO A MÉDIA ARITMÉTICA DOSELEMENTOS ARMAZENADOS NESTE ARRAY QUE SÃO ÍMPARES.
 */
public class Exercicio_03 {

}
